#include "logic/decklists.h"

#include "logic/cards/BoulderfistOgre.h"

const Card BOULDERFIST_OGRE = BoulderfistOgre();

const DeckList ogre_deck = {
    BOULDERFIST_OGRE, BOULDERFIST_OGRE, BOULDERFIST_OGRE, BOULDERFIST_OGRE, BOULDERFIST_OGRE, BOULDERFIST_OGRE,
    BOULDERFIST_OGRE, BOULDERFIST_OGRE, BOULDERFIST_OGRE, BOULDERFIST_OGRE, BOULDERFIST_OGRE, BOULDERFIST_OGRE,
    BOULDERFIST_OGRE, BOULDERFIST_OGRE, BOULDERFIST_OGRE, BOULDERFIST_OGRE, BOULDERFIST_OGRE, BOULDERFIST_OGRE,
    BOULDERFIST_OGRE, BOULDERFIST_OGRE, BOULDERFIST_OGRE, BOULDERFIST_OGRE, BOULDERFIST_OGRE, BOULDERFIST_OGRE,
    BOULDERFIST_OGRE, BOULDERFIST_OGRE, BOULDERFIST_OGRE, BOULDERFIST_OGRE, BOULDERFIST_OGRE, BOULDERFIST_OGRE,
};