#include "logic/decklists.h"

const DeckList ogre_deck = {
    BOULDERFIST_OGRE, BOULDERFIST_OGRE, BOULDERFIST_OGRE, BOULDERFIST_OGRE, BOULDERFIST_OGRE, BOULDERFIST_OGRE,
    BOULDERFIST_OGRE, BOULDERFIST_OGRE, BOULDERFIST_OGRE, BOULDERFIST_OGRE, BOULDERFIST_OGRE, BOULDERFIST_OGRE,
    BOULDERFIST_OGRE, BOULDERFIST_OGRE, BOULDERFIST_OGRE, BOULDERFIST_OGRE, BOULDERFIST_OGRE, BOULDERFIST_OGRE,
    BOULDERFIST_OGRE, BOULDERFIST_OGRE, BOULDERFIST_OGRE, BOULDERFIST_OGRE, BOULDERFIST_OGRE, BOULDERFIST_OGRE,
    BOULDERFIST_OGRE, BOULDERFIST_OGRE, BOULDERFIST_OGRE, BOULDERFIST_OGRE, BOULDERFIST_OGRE, BOULDERFIST_OGRE,
};